[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_pgsql", "php82Extensions.pgsql", "php82Extensions.redis", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Extensions.gd", "php82Extensions.mbstring", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.xml", "php82Extensions.bcmath", "php82Extensions.fileinfo", "php82Extensions.opcache"]

[phases.install]
cmds = [
    "mkdir -p storage/framework/cache",
    "mkdir -p storage/framework/sessions",
    "mkdir -p storage/framework/views",
    "mkdir -p storage/logs"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."